import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCuNZLUtp
zHTOgcr4BGQ2mSAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIPivcr0GgyqWapD0
poICjJFA37rEFb7bh3HUr7bVnzcXAAAAkC8bz0eulKnSge9URO11dgR/f4nms4szX77yCF
iuk3RSCrzUTdPETmlHb3/iDnEH9A78tye0v+Hx9DPrMYbaKGvICPy6cFU3WHXGTPK8aO/J
F4++O7TMcMnZ3aKHZACsYf0mDQiNbUXGL+1VoRDh8XBYbOI9Dy7KNz3cZuGCEBqfuKk8mL
KbVPGSSrzLwdJTdA==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
